version: "3"

services:
  haproxy_docker:
    build:
      context: .
    container_name: haproxy
    restart: always
    hostname: haproxy
    ports:
      - "8080:80"                         # Open port 8080 public -> 80
      - "443:443"                         # Open port 443  public -> 443
